spring:
  application:
    name: M_BL5_G1_SU25

  datasource:
    url: jdbc:mysql://localhost:3306/smartshop?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 123456


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  security:
    user:
      name: admin
      password: admin
      roles: ADMIN

server:
  port: 8080
