server:
  port: 8080
  servlet:
    context-path: /rms

spring:
  datasource:
    url: "jdbc:sqlserver://localhost:1433;database=SWP391_BL5_SU25;trustServerCertificate=true"
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: dbo

    database-platform: org.hibernate.dialect.SQLServerDialect
    logging:
      level:
        org.hibernate.SQL: DEBUG
        org.hibernate.tool.schema: DEBUG