#spring.application.name=M_BL5_G1_SU25

# Database Configuration for MySQL
#spring.datasource.url=jdbc:mysql://localhost:3306/smartshop?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=123456
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Configuration
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Thymeleaf Configuration
#spring.thymeleaf.cache=false
#spring.thymeleaf.prefix=classpath:/templates/
#spring.thymeleaf.suffix=.html

# Web Configuration
#server.port=8080

# Security Configuration (temporary disable for development)
#spring.security.user.name=admin
#spring.security.user.password=admin
#spring.security.user.roles=ADMIN
spring:
  application:
    name: M_BL5_G1_SU25

  datasource:
    url: jdbc:mysql://localhost:6379/smartshop?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: admin
    password: Dungnche140981
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  security:
    user:
      name: admin
      password: admin
      roles: ADMIN

server:
  port: 8080



