server:
  port: 8080
  shutdown: graceful
  servlet:
    session:
      timeout: 30m
      cookie:
        max-age: 1800
        same-site: lax
        secure: false
        http-only: true

spring:
  application:
    name: SWP391-Online-Shopping

  lifecycle:
    timeout-per-shutdown-phase: 10s

  session:
    store-type: none

  # Local SQL Server Configuration
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=SWP391_BL5_SU25;trustServerCertificate=true;encrypt=false
    username: sa
    password: 123456
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10
      minimum-idle: 5

  # Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true

  # SMTP Configuration for Gmail
  mail:
    host: smtp.gmail.com
    port: 587
    username: smartshopforeveryone@gmail.com
    password: ynzx kxzg upzh jhvk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  # Thymeleaf Configuration
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML

# Application specific properties
app:
  base-url: http://localhost:8080

# Logging configuration
logging:
  level:
    spring.backend.m_bl5_g1_su25: DEBUG
    org.springframework.mail: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE