server:
  port:
  shutdown: graceful
  servlet:
    session:
      timeout:
      cookie:
        max-age:
        same-site: lax
        secure: false
        http-only: true

spring:
  application:
    name: SWP391-Online-Shopping

  lifecycle:
    timeout-per-shutdown-phase: 10s

  session:
    store-type: none

  datasource:
    url:
    username:
    password:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10
      minimum-idle: 5

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: false


  thymeleaf:
    cache: false


logging:
  level:
    root: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    org.springframework.jdbc: WARN